version: 0.0.{build}

branches:
  only:
    - master
    - dev

image: Visual Studio 2017 
platform:
  - x64

cache:
  - node_modules 
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

init:
  - git config --global core.autocrlf input 

install:
  - ps: Install-Product node 11 x64 
  - git reset --hard HEAD 
  - yarn 
  - node --version
  - yarn --version 

build_script:
  - yarn release

test: off