version: 0.0.{build}

branches:
  only:
    - master
    - dev

image: Visual Studio 2017 
platform:
  - x64

environment:
  GH_TOKEN:
    secure: rI+sosKKgMCLnb6Bns0gP3V7PXDj4UaPt5lAGEhknpayucW42OSMrgryLsXk0c7e

cache:
  - node_modules 
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

init:
  - git config --global core.autocrlf input 

install:
  - choco install --version nodejs 11.10.0
  - git reset --hard HEAD 
  - yarn 
  - node --version
  - yarn --version 

build_script:
  - yarn release

test: off